AWSTemplateFormatVersion: "2010-09-09"
Description: "Artifact Repository Resources of load test"
Parameters:
  RootStackName:
    Type: "String"
Resources:
  ArtifactRepository:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Retain"
    Properties:
      AccessControl: "BucketOwnerFullControl"
Outputs:
  Name:
    Description: "S3 Backet Name of Artifact Repository"
    Value: !Ref ArtifactRepository
