AWSTemplateFormatVersion: "2010-09-09"
Description: "Load Testing Pipeline Resources"
Parameters:
  CFnTemplateBucketName:
    Type: "String"
  CFnTemplateBucketRegion:
    Type: "String"
Mappings:
  Constraints:
    Project:
      Name: "load-testing-on-aws"
  CFn:
    Path:
      SourceCodeRepository: "pipeline/sourcecode-repository.yml"
      ArtifactRepository: "pipeline/artifact-repository.yml"
      ContainerImageRepository: "pipeline/containerimage-repository.yml"
      BuildContainerImageProject: "pipeline/build-containerimage-project.yml"
      RunLoadTestProject: "pipeline/run-load-testing-project.yml"
      Pipeline: "pipeline/pipeline.yml"
Conditions:
  IsUsEast1: !Equals [ !Ref CFnTemplateBucketRegion, "us-east-1" ]
  IsUsEast2: !Equals [ !Ref CFnTemplateBucketRegion, "us-east-2" ]
Resources:
  SourceCodeRepository:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub:
          - "https://s3${Region}.amazonaws.com/${CFnTemplateBucketName}/${ProjectName}/${Path}"
          - {
              Region: !If [ IsUsEast1, "", !If [ IsUsEast2, !Sub ".${CFnTemplateBucketRegion}", !Sub "-${CFnTemplateBucketRegion}" ] ],
              ProjectName: !FindInMap [ Constraints, Project, Name ],
              Path: !FindInMap [ CFn, Path, SourceCodeRepository ]
            }
      TimeoutInMinutes: "5"
      Parameters:
        RootStackName: !Ref AWS::StackName
  ArtifactRepository:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub:
          - "https://s3${Region}.amazonaws.com/${CFnTemplateBucketName}/${ProjectName}/${Path}"
          - {
              Region: !If [ IsUsEast1, "", !If [ IsUsEast2, !Sub ".${CFnTemplateBucketRegion}", !Sub "-${CFnTemplateBucketRegion}" ] ],
              ProjectName: !FindInMap [ Constraints, Project, Name ],
              Path: !FindInMap [ CFn, Path, ArtifactRepository ]
            }
      TimeoutInMinutes: "5"
      Parameters:
        RootStackName: !Ref AWS::StackName
  ServerContainerImageRepository:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub:
          - "https://s3${Region}.amazonaws.com/${CFnTemplateBucketName}/${ProjectName}/${Path}"
          - {
              Region: !If [ IsUsEast1, "", !If [ IsUsEast2, !Sub ".${CFnTemplateBucketRegion}", !Sub "-${CFnTemplateBucketRegion}" ] ],
              ProjectName: !FindInMap [ Constraints, Project, Name ],
              Path: !FindInMap [ CFn, Path, ContainerImageRepository ]
            }
      TimeoutInMinutes: "5"
      Parameters:
        RootStackName: !Ref AWS::StackName
  ClientContainerImageRepository:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub:
          - "https://s3${Region}.amazonaws.com/${CFnTemplateBucketName}/${ProjectName}/${Path}"
          - {
              Region: !If [ IsUsEast1, "", !If [ IsUsEast2, !Sub ".${CFnTemplateBucketRegion}", !Sub "-${CFnTemplateBucketRegion}" ] ],
              ProjectName: !FindInMap [ Constraints, Project, Name ],
              Path: !FindInMap [ CFn, Path, ContainerImageRepository ]
            }
      TimeoutInMinutes: "5"
      Parameters:
        RootStackName: !Ref AWS::StackName
  BuildServerContainerImage:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub:
          - "https://s3${Region}.amazonaws.com/${CFnTemplateBucketName}/${ProjectName}/${Path}"
          - {
              Region: !If [ IsUsEast1, "", !If [ IsUsEast2, !Sub ".${CFnTemplateBucketRegion}", !Sub "-${CFnTemplateBucketRegion}" ] ],
              ProjectName: !FindInMap [ Constraints, Project, Name ],
              Path: !FindInMap [ CFn, Path, BuildContainerImageProject ]
            }
      TimeoutInMinutes: "5"
      Parameters:
        RootStackName: !Ref AWS::StackName
        SourceCodeRepositoryName: !GetAtt [ SourceCodeRepository, Outputs.Name ]
        TargetContainerImage: "server"
        ContainerRepositoryName: !GetAtt [ ServerContainerImageRepository, Outputs.Name ]
  BuildClientContainerImage:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub:
          - "https://s3${Region}.amazonaws.com/${CFnTemplateBucketName}/${ProjectName}/${Path}"
          - {
              Region: !If [ IsUsEast1, "", !If [ IsUsEast2, !Sub ".${CFnTemplateBucketRegion}", !Sub "-${CFnTemplateBucketRegion}" ]],
              ProjectName: !FindInMap [ Constraints, Project, Name ],
              Path: !FindInMap [ CFn, Path, BuildContainerImageProject ]
            }
      TimeoutInMinutes: "5"
      Parameters:
        RootStackName: !Ref AWS::StackName
        SourceCodeRepositoryName: !GetAtt [ SourceCodeRepository, Outputs.Name ]
        TargetContainerImage: "client"
        ContainerRepositoryName: !GetAtt [ ClientContainerImageRepository, Outputs.Name ]

  RunLoadTestProject:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub:
          - "https://s3${Region}.amazonaws.com/${CFnTemplateBucketName}/${ProjectName}/${Path}"
          - {
              Region: !If [ IsUsEast1, "", !If [ IsUsEast2, !Sub ".${CFnTemplateBucketRegion}", !Sub "-${CFnTemplateBucketRegion}" ] ],
              ProjectName: !FindInMap [ Constraints, Project, Name ],
              Path: !FindInMap [ CFn, Path, RunLoadTestProject ]
            }
      TimeoutInMinutes: "5"
      Parameters:
        RootStackName: !Ref AWS::StackName
        SourceCodeRepositoryName: !GetAtt [ SourceCodeRepository, Outputs.Name ]
        ClusterName: !Sub "${AWS::StackName}-load-test-cluster"
        JMeterServerTaskName: !Sub "${AWS::StackName}-jmeter-server-task"
        JMeterClientTaskName: !Sub "${AWS::StackName}-jmeter-client-task"
        ServerContainerImageRepository: !GetAtt ServerContainerImageRepository.Outputs.Name
        ClientContainerImageRepository: !GetAtt ClientContainerImageRepository.Outputs.Name
        RuntimeStackName: !Sub "${AWS::StackName}-load-test-runtime"
  Pipeline:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub:
          - "https://s3${Region}.amazonaws.com/${CFnTemplateBucketName}/${ProjectName}/${Path}"
          - {
              Region: !If [ IsUsEast1, "", !If [ IsUsEast2, !Sub ".${CFnTemplateBucketRegion}", !Sub "-${CFnTemplateBucketRegion}" ] ],
              ProjectName: !FindInMap [ Constraints, Project, Name ],
              Path: !FindInMap [ CFn, Path, Pipeline ]
            }
      TimeoutInMinutes: "5"
      Parameters:
        RootStackName: !Ref AWS::StackName
        SourceCodeRepositoryName: !GetAtt SourceCodeRepository.Outputs.Name
        ArtifactRepositoryName: !GetAtt ArtifactRepository.Outputs.Name
        RunLoadTestProjectName: !GetAtt RunLoadTestProject.Outputs.ProjectName
        ClusterName: !Sub "${AWS::StackName}-load-test-cluster"
        ServerContainerImageRepository: !GetAtt ServerContainerImageRepository.Outputs.Name
        ClientContainerImageRepository: !GetAtt ServerContainerImageRepository.Outputs.Name
        BuildServerContainerProjectName: !GetAtt BuildServerContainerImage.Outputs.ProjectName
        BuildClientContainerProjectName: !GetAtt BuildClientContainerImage.Outputs.ProjectName
        JMeterServerTaskName: !Sub "${AWS::StackName}-jmeter-server-task"
        JMeterClientTaskName: !Sub "${AWS::StackName}-jmeter-client-task"
        RuntimeStackName: !Sub "${AWS::StackName}-load-test-runtime"
Outputs:
  SourceCodeRepositoryName:
    Value: !GetAtt SourceCodeRepository.Outputs.Name
